'This script has been generated by PowerPCB's VB Script Wizard on 7/19/2018 1:52:02 PM
'It will create reports in Microsoft Excel Format.
'You can use the following code as a skeleton for your own VB scripts

'Array of column names. You can modify it to rename columns
Const Columns = Array("Name", "Part Type", "PCB Decal", "Orientation", "Pins", "Value", "Glued", "SMD", "Layer Name", "Layer Number", "Position X", "Position Y")
Dim fname As String

Sub Main
	'Make report file name from current schematic file name
	fname = ActiveDocument
	If fname = "" Then
		fname = "Untitled"
		report = DefaultFilePath & "\default.txt"
	Else
		nm = Left(fname, Len( fname) - 4)
		report = DefaultFilePath & "\" & nm & ".txt"
	End If
	Open report For Output As #1

	StatusBarText = "Generating report..."
	'Output table header
	For i = 0 to UBound(Columns)
		OutCell Columns(i)
	Next
	Print #1
	'Output table rows
	For Each part in ActiveDocument.Components
		OutCell part.Name
		OutCell part.PartType
		OutCell part.Decal
		OutCell part.orientation
		OutCell part.Pins.Count
		OutCell AttrVal(part, "Value")
		OutCell Format(part.Glued, "Yes/No")
		OutCell Format(part.IsSMD, "Yes/No")
		OutCell ActiveDocument.LayerName(part.layer)
		OutCell part.layer
		OutCell Format(part.PositionX, "0.000")
		OutCell Format(part.PositionY, "0.000")
		Print #1
	Next part

	StatusBarText = ""
	Close #1
	ExportToExcel report
	Kill report
End Sub

Function AttrVal (obj As Object, nm As String)
	AttrVal = IIf(obj.Attributes(nm) Is Nothing, "", obj.Attributes(nm))
End Function

Sub ExportToExcel (TextFile As String)
	On Error GoTo ExcelError	' Enable error trapping.
	Set xl =  CreateObject("Excel.Application")
	xl.Visible = True
	xl.Workbooks.OpenText FileName:=TextFile, Tab:=True
	'save worksheet as native Excel document
	NativeFile = Left(TextFile, Len(TextFile) - 4) + ".xls"
	xl.ActiveWorkbook.SaveAs Filename:= NativeFile, FileFormat:= -4143
	xl.Range("A1:L1").Font.Bold = True
	xl.Range("A1:L1").NumberFormat = "@"
	xl.Range("A1:L1").AutoFilter
	xl.ActiveSheet.UsedRange.Columns.AutoFit
	'Output Report Header
	xl.Rows(1).Insert
	xl.Rows(1).Cells(1) = Space(1) & "Part Report for " & fname & " on " & Now
	xl.Rows(2).Insert
	xl.Rows(1).Font.bold = True
	On Error GoTo 0 ' Disable error trapping. 
	Exit Sub    

ExcelError:
	if Err.Number = 1004& then xl.Quit	'Excel could not save the file. Terminate Excel
	MsgBox Err.Description, vbExclamation, "Error Running Excel"
	On Error GoTo 0 ' Disable error trapping.    
	Exit Sub
End Sub

Sub OutCell (txt As String)
	Print #1, txt; vbTab;
End Sub
